# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##find the memory size of any array

In [ ]:
my_array = np.zeros((10, 10), dtype=np.int32)

memory_size_bytes = my_array.nbytes

memory_size_bytes

400

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand()

0.2734014221808224

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

array([-0.28816532, -0.62648351, -1.54607012, -0.30802862,  1.2642203 ,
       -0.97640247,  0.751881  ,  2.09135447, -2.34988568, -0.77408872,
       -0.02669207, -1.34654171, -2.99458612, -0.41227893,  0.41094371,
        0.46504681, -0.26889737,  0.8114877 , -0.87958767,  0.02778704,
        1.71437162, -1.83878894, -2.32819726, -1.00052691, -0.24283276])

#### Create the following matrix:

In [ ]:
 np.random.rand(10, 10)

array([[0.91582067, 0.1663035 , 0.11322517, 0.52734512, 0.11300837,
        0.18181318, 0.56419771, 0.41807404, 0.5441538 , 0.27913138],
       [0.84127101, 0.48455654, 0.26309972, 0.83662204, 0.91509872,
        0.56624589, 0.60548417, 0.16580265, 0.89984444, 0.78635183],
       [0.34610416, 0.43407647, 0.59540277, 0.55900193, 0.52743116,
        0.76637599, 0.16189508, 0.08509705, 0.2486394 , 0.43007536],
       [0.54910066, 0.29263883, 0.8531846 , 0.99020086, 0.13287146,
        0.09948404, 0.06684663, 0.07022759, 0.93146195, 0.40418834],
       [0.98694628, 0.6427026 , 0.59138444, 0.9935525 , 0.35269323,
        0.5661385 , 0.7865833 , 0.26129338, 0.80344517, 0.49467731],
       [0.88578868, 0.65176335, 0.35497175, 0.434732  , 0.16900829,
        0.30509903, 0.38878391, 0.42427018, 0.22492393, 0.93928236],
       [0.44916371, 0.54963761, 0.85792816, 0.876137  , 0.56701149,
        0.15462052, 0.45508876, 0.13887642, 0.17989542, 0.13922068],
       [0.60576888, 0.0286762 , 0.0888960

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
ans = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])
ans

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
arr=[10,20,30]
answer=np.mean(arr)
answer

20.0

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.array([[2], [7], [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
math = np.arange(16,26).reshape(2,5)
math

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

####Create a 10*10  matrix with 1 on the border and 0 inside

In [ ]:
n = np.zeros((10, 10), dtype=int)

# Set the border elements to 1
n[0, :] = 1
n[-1, :] = 1
n[:, 0] = 1
n[:, -1] = 1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### find common values between two arrays

In [ ]:
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])

In [ ]:
np.intersect1d(x1, x2)


array([2, 4, 8])

####You can use flatten to flatten your array into a 1D array

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a=x.flatten()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Great Job!